version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks: 
      - node-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node_app

  node_app:
    build: ./node_app
    container_name: node_app
    volumes:
      - ./node_app:/usr/src
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    command: npm run start
    networks: 
      - node-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=testdb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    networks: 
      - node-network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  node-network:
    name: node-network
    driver: bridge

volumes:
  mysql_data: