version: '3'

services:

  node_app:
    build: ./node_app
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - ./node_app:/usr/src/node_app
      # - /usr/src/node_app/node_modules # link simbolico - volume anonimo
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s sh -c "npm install && npm run start"
    networks: 
      - node-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks: 
      - node-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node_app

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    networks: 
      - node-network
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    
networks:
  node-network:
    name: node-network
    driver: bridge

volumes:
  mysql_data: