version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node_app

  node_app:
    build: ./node_app
    container_name: node_app
    volumes:
      - ./node_app:/usr/src/app
    entrypoint: dockerize -wait tcp://docker-nodejs-mysql-1:3306 -timeout 20s docker-entrypoint.sh
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=testdb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
